# Generated by Django 2.1.8 on 2019-08-25 16:30

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190824_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='image',
            field=models.ImageField(upload_to='img', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='goodsimg',
            name='image',
            field=models.ImageField(upload_to='img', verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='store',
            name='descripton',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.ImageField(upload_to='img', verbose_name='logo图'),
        ),
    ]
