# Generated by Django 2.1.8 on 2019-08-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190831_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='up',
            field=models.BooleanField(default=False, verbose_name='商品上架'),
        ),
    ]
